### ISSUE TITLE
Missing custom component files

### ISSUE THREAD

**Issue by loryanstrant** [cloudbr34k84/home-assistant-pocketsmith#1]
I'd very much like to use this, but the instructions say to download the files - but unfortunately there's nothing in this repo other than the README.md file. :-)

**Comment by cloudbr34k84** [comment]
Yeah I know sorry, just haven't had a chance to create the files..
I'll do it tomorrow

**Comment by cloudbr34k84** [comment]
@loryanstrant Try now mate. Bear with me im learning all this so hopefully this works for you

**Comment by loryanstrant** [comment]
Nice work, thank you!
I attempted the same using ChatGPT after seeing the files weren't in this repo, but couldn't get it to work properly - so you've gotten a lot further than me! :-)
